import './globals.css'
import Navegacion from './components/nav'

export const metadata = {
  title: 'Primer Proyecto',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navegacion/>
      <main className='container mx-auto h-[calc(100vh-7rem)] 
                       flex justify-center items-center'>
         {children}
      </main>
      </body>
    </html>
  )
}
